[workspace]
resolver = "2"
members = [
    "vidwall",
    "vidplayer",
    "ffmpeg/types",
    "ffmpeg/source",
    "ffmpeg/decode",
    "ffmpeg/transform",
    "ffmpeg/encode",
    "ffmpeg/sink",
]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT"

[profile.release]
opt-level = 3
lto = true
