[workspace]
resolver = "2"
members = [
    "vidwall",
    "vidplayer",
    "vidproxy",
    "wdv3",
    "wdv3-proto",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false

[workspace.dependencies]
ffmpeg-types = { git = "https://github.com/tibellium/crates", rev = "1b6a1ed49c2e3eb4b0129b0630a421067bb9397a" }
ffmpeg-source = { git = "https://github.com/tibellium/crates", rev = "1b6a1ed49c2e3eb4b0129b0630a421067bb9397a" }
ffmpeg-decode = { git = "https://github.com/tibellium/crates", rev = "1b6a1ed49c2e3eb4b0129b0630a421067bb9397a" }
ffmpeg-transform = { git = "https://github.com/tibellium/crates", rev = "1b6a1ed49c2e3eb4b0129b0630a421067bb9397a" }
ffmpeg-encode = { git = "https://github.com/tibellium/crates", rev = "1b6a1ed49c2e3eb4b0129b0630a421067bb9397a" }
ffmpeg-sink = { git = "https://github.com/tibellium/crates", rev = "1b6a1ed49c2e3eb4b0129b0630a421067bb9397a" }

[profile.release]
opt-level = 3
lto = true
