[workspace]
resolver = "2"
members = [
    "vidwall",
    "vidplayer",
    "vidproxy",
    "drm-sniff",
]

[workspace.package]
version = "0.0.0"
edition = "2024"
publish = false

[workspace.dependencies]
ffmpeg-types = { git = "https://github.com/tibellium/crates", rev = "2e467ad4307a36cc79dab054d018e452437ecf27" }
ffmpeg-source = { git = "https://github.com/tibellium/crates", rev = "2e467ad4307a36cc79dab054d018e452437ecf27" }
ffmpeg-decode = { git = "https://github.com/tibellium/crates", rev = "2e467ad4307a36cc79dab054d018e452437ecf27" }
ffmpeg-transform = { git = "https://github.com/tibellium/crates", rev = "2e467ad4307a36cc79dab054d018e452437ecf27" }
ffmpeg-encode = { git = "https://github.com/tibellium/crates", rev = "2e467ad4307a36cc79dab054d018e452437ecf27" }
ffmpeg-sink = { git = "https://github.com/tibellium/crates", rev = "2e467ad4307a36cc79dab054d018e452437ecf27" }

[profile.release]
opt-level = 3
lto = true
