[package]
name = "drm-widevine-proto"
version = { workspace = true }
edition = { workspace = true }
publish = { workspace = true }

[dependencies]
drm-core = { path = "../core" }
prost = "0.14"

[build-dependencies]
prost-build = "0.14"
